
import { Certification, ComparisonData } from '../types';

export const fetchCertificationData = async (): Promise<Certification[]> => {
  try {
    // Fetch data from a local static file instead of Gemini
    const response = await fetch('/data/certifications.json');
    if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
    }
    const data = await response.json();
    
    if (data && Array.isArray(data.certifications)) {
        // Post-processing for pass scores on a 1000-point scale
        return data.certifications.map((cert: Certification) => {
            if (cert.passScore > 100) {
                return { ...cert, passScore: Math.round((cert.passScore / 1000) * 100) };
            }
            return cert;
        });
    } else {
        console.error("Unexpected JSON structure:", data);
        throw new Error("Failed to parse certification data: Invalid structure.");
    }

  } catch (error) {
    console.error("Error fetching or parsing certification data from file:", error);
    throw new Error("Could not retrieve certification data from local file.");
  }
};

export const askGeminiAboutCerts = async (question: string, certifications: Certification[]): Promise<string> => {
  // This function is now a placeholder and does not call the Gemini API.
  // It returns a static message to the user.
  console.log("Attempted to ask Gemini (currently disconnected):", question, "with data:", certifications);
  return Promise.resolve(
    "The live 'Ask Gemini' feature is currently disconnected.\n\nThis response is a placeholder. In a production environment, this feature would be connected to a secure backend that calls the Gemini API to answer your question based on the provided certification data."
  );
};

export const fetchComparisonData = async (certifications: Certification[]): Promise<ComparisonData[]> => {
  if (certifications.length < 2) return [];

  // Create a consistent key by sorting certification IDs alphabetically
  const key = certifications.map(c => c.id).sort().join('_');

  try {
    // Fetch from a local static file of pre-generated comparisons
    const response = await fetch('/data/comparisons.json');
     if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
    }
    const allComparisons = await response.json();

    if (allComparisons && allComparisons[key]) {
      // If a pre-generated comparison exists for this key, return it
      return allComparisons[key];
    } else {
      // If not, return a fallback message to avoid crashing the UI
      console.warn(`No pre-generated comparison found for key: ${key}. Returning fallback data.`);
      return certifications.map(cert => ({
          id: cert.id,
          targetAudience: "Comparison data not available in static file.",
          careerBenefit: "This data would normally be generated by Gemini.",
          jobMarketBenefit: "Please connect to a backend to see live data.",
          estimatedCost: `$${cert.cost} (exam only)`,
          officialLink: cert.officialLink,
      }));
    }
  } catch (error) {
    console.error("Error fetching or parsing comparison data from file:", error);
    throw new Error("Could not retrieve comparison data from local file.");
  }
};
