import { Certification, ComparisonData } from '../types';

const BASE_URL = import.meta.env.VITE_API_BASE_URL || '';

export const fetchCertificationData = async (): Promise<Certification[]> => {
  try {
    // In production (SWA), we'll use the cloud API.
    // In dev (npm run dev), we keep using the local JSON file.
    const useCloudApi = !import.meta.env.DEV && !!BASE_URL;

    const url = useCloudApi
      ? `${BASE_URL}/api/certifications`
      : '/data/certifications.json';

    console.log('Fetching certifications from:', url);

    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data = await response.json();

    let certifications: Certification[];

    if (Array.isArray(data)) {
      certifications = data as Certification[];
    } else if (data && Array.isArray((data as any).certifications)) {
      certifications = (data as any).certifications as Certification[];
    } else {
      console.error('Unexpected JSON structure:', data);
      throw new Error('Failed to parse certification data.');
    }

    // If passScore is 0–1000, convert to percentage.
    return certifications.map((cert: Certification) => {
      if (cert.passScore > 100) {
        return {
          ...cert,
          passScore: Math.round((cert.passScore / 1000) * 100),
        };
      }
      return cert;
    });
  } catch (error) {
    console.error('Error fetching or parsing certification data:', error);
    throw error;
  }
};

export const fetchComparisonData = async (): Promise<ComparisonData[]> => {
  try {
    const certifications = await fetchCertificationData();

    return certifications.map(cert => ({
      id: cert.id,
      targetAudience: 'Comparison data not available in static file.',
      careerBenefit: 'This data would normally be generated by Gemini.',
      jobMarketBenefit: 'Please connect to a backend to see live data.',
      estimatedCost: `$${cert.cost} (exam only)`,
      officialLink: cert.officialLink,
    }));
  } catch (error) {
    console.error('Error generating comparison data:', error);
    throw new Error('Could not retrieve comparison data.');
  }
};
